language: rust
rust:
- stable
- beta
- nightly
script:
- cargo build --verbose
- cargo test --verbose
- cargo doc --verbose
- cargo build --verbose --no-default-features
- cargo test --verbose --no-default-features
