#!/bin/sh
set -eu

cd "$(dirname "$(realpath "$0")")"

triple="$(rustc -Vv | awk -F ': ' '{ if($1 == "host") print $2 }')"

cargo +nightly build \
    -Z build-std=core,panic_abort \
    --target "$triple" \
    --release
